### ISSUE TITLE
Decide how theme JS files are added

### ISSUE THREAD

**Issue by andrew-147** [lemberg/draft-theme#20]
Single or multiple files usage.

**Comment by andrew-147** [comment]
- `STARTER/js/bundle/components/*.js` files to be included in `STARTER /js/bundle/bundle.js`
- standalone js files to be placed in `STARTER /js/standalone` folder
- libraries (chosen, masonry etc) to be placed in `core/libraries` folder and are managed by composer

**Comment by bogdan-hepting** [comment]
Fixed in #32
