### ISSUE TITLE
Add clean paragraph related templates

### ISSUE THREAD

**Issue by T2L** [lemberg/draft-theme#4]
- Entity Reference Revision field
- Paragraph item

**Comment by andrew-147** [comment]
paragraph.html.twig example:
`{%
set classes = [
'paragraph',
'paragraph--type--' ~ paragraph.bundle|clean_class,
view_mode ? 'paragraph--view-mode--' ~ view_mode|clean_class,
]
%}

{% set rendered_content = content|without('') %}

<div{{ attributes.addClass(classes) }} {{ styles }}>
  <div class="paragraph-content">
    {{ rendered_content }}
  </div>
</div>`

**Comment by Crazylord** [comment]
PR: #22
